# -*- coding: utf-8 -*-
"""car_count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ZStlGxzMh9l-kFrIuRfq1JVqzRAqssy
"""

import time
import cv2
import matplotlib.pyplot as plt
import cvlib as cv
from cvlib.object_detection import draw_bbox
starttimevar = time.time()
im = cv2.imread('carjam.jpeg')
bbox, label, conf = cv.detect_common_objects(im)
output_image = draw_bbox(im, bbox, label, conf)
plt.imshow(output_image)
plt.show()
print('Number of cars in the image is '+ str(label.count('car')))
elapsetime = time.time() - starttimevar
print(elapsetime)

! pip install cvlib

